apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-ai-pgbouncer-config
  namespace: cluster-ai
  labels:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: cluster-ai
data:
  pgbouncer.ini: |
    [databases]
    cluster_ai = host=cluster-ai-postgres-postgresql.cluster-ai.svc.cluster.local port=5432 dbname=cluster_ai

    [pgbouncer]
    listen_addr = 0.0.0.0
    listen_port = 6432
    auth_type = md5
    auth_file = /etc/pgbouncer/userlist.txt
    logfile = /dev/stdout
    pidfile = /var/run/pgbouncer/pgbouncer.pid
    admin_users = cluster_ai
    stats_users = cluster_ai

    # Connection pooling
    pool_mode = transaction
    max_client_conn = 1000
    default_pool_size = 20
    min_pool_size = 5
    reserve_pool_size = 5
    reserve_pool_timeout = 3
    max_db_connections = 50
    max_user_connections = 50

    # Performance tuning
    server_idle_timeout = 30
    server_lifetime = 3600
    server_connect_timeout = 15
    server_login_retry = 15
    query_timeout = 120
    query_wait_timeout = 120
    client_idle_timeout = 0
    client_login_timeout = 60

    # TCP settings
    tcp_keepalive = 1
    tcp_keepcnt = 5
    tcp_keepidle = 30
    tcp_keepintvl = 30

    # Logging
    log_connections = 1
    log_disconnections = 1
    log_pooler_errors = 1
    verbose = 0
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-ai-pgbouncer-secret
  namespace: cluster-ai
  labels:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: cluster-ai
type: Opaque
data:
  userlist.txt: Y2x1c3Rlcl9haSBtZDU3MzY5MzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMK
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-ai-pgbouncer
  namespace: cluster-ai
  labels:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: cluster-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: pgbouncer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pgbouncer
        app.kubernetes.io/component: database
    spec:
      containers:
      - name: pgbouncer
        image: edoburu/pgbouncer:1.18
        ports:
        - containerPort: 6432
          name: pgbouncer
        volumeMounts:
        - name: pgbouncer-config
          mountPath: /etc/pgbouncer
        - name: pgbouncer-secret
          mountPath: /etc/pgbouncer-secret
        env:
        - name: DB_USER
          value: "cluster_ai"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cluster-ai-postgres-postgresql
              key: password
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          tcpSocket:
            port: 6432
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 6432
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: pgbouncer-config
        configMap:
          name: cluster-ai-pgbouncer-config
      - name: pgbouncer-secret
        secret:
          secretName: cluster-ai-pgbouncer-secret
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-ai-pgbouncer
  namespace: cluster-ai
  labels:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: cluster-ai
spec:
  ports:
  - port: 6432
    targetPort: 6432
    name: pgbouncer
  selector:
    app.kubernetes.io/name: pgbouncer
  type: ClusterIP
