# Configuração do Cluster AI - Servidor
NODE_ROLE=server
NODE_IP=192.168.0.2
NODE_IP_SECONDARY=192.168.0.3
NODE_HOSTNAME=note-dago
CLUSTER_NAME=cluster-ai-main
DASK_SCHEDULER_PORT=8786
DASK_DASHBOARD_PORT=8787
OLLAMA_PORT=11434
OPENWEBUI_PORT=3000
WORKER_MANJARO_IP=192.168.0.4
