# Configuração do Cluster AI

[cluster]
node_role = server
node_ip = 192.168.0.2
node_hostname = localhost
cluster_name = cluster-ai-main

[dask]
scheduler_port = 8786
dashboard_port = 8787
n_workers = 2
threads_per_worker = 2
auth_token = "seu_token_secreto_aqui_12345"

[services]
ollama_port = 11434
openwebui_port = 3000
