global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@cluster-ai.com'
  smtp_auth_username: 'alerts@cluster-ai.com'
  smtp_auth_password: '${SMTP_PASSWORD}'

templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'
  routes:
  - match:
      severity: critical
    receiver: 'critical-email'
    continue: true
  - match:
      severity: warning
    receiver: 'warning-email'
  - match:
      alertname: Watchdog
    receiver: 'null'

receivers:
- name: 'null'
- name: 'email'
  email_configs:
  - to: 'devops@cluster-ai.com'
    send_resolved: true
- name: 'critical-email'
  email_configs:
  - to: 'oncall@cluster-ai.com'
    send_resolved: true
- name: 'warning-email'
  email_configs:
  - to: 'alerts@cluster-ai.com'
    send_resolved: true

# Slack integration (optional)
- name: 'slack'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#alerts'
    send_resolved: true
    title: '{{ .GroupLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Severity:* {{ .Labels.severity }}
      *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
      {{ end }}

# PagerDuty integration (optional)
- name: 'pagerduty'
  pagerduty_configs:
  - service_key: '${PAGERDUTY_SERVICE_KEY}'
    description: '{{ .GroupLabels.alertname }}'
    details:
      firing: '{{ .Alerts.Firing | len }}'
      resolved: '{{ .Alerts.Resolved | len }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
