apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-ai-backend
  namespace: cluster-ai
  labels:
    app: cluster-ai
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cluster-ai
      component: backend
  template:
    metadata:
      labels:
        app: cluster-ai
        component: backend
    spec:
      containers:
      - name: backend
        image: cluster-ai-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: cluster-ai-config
              key: ENVIRONMENT
        - name: REDIS_URL
          value: "redis://cluster-ai-redis:6379"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cluster-ai-secrets
              key: POSTGRES_PASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: cluster-ai-secrets
              key: SECRET_KEY
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: cluster-ai-secrets
              key: JWT_SECRET_KEY
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: cluster-ai-secrets
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: cluster-ai-secrets
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          value: "cluster-ai-postgres"
        - name: POSTGRES_PORT
          value: "5432"
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: logs
          mountPath: /app/logs
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 15
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
      volumes:
      - name: data
        emptyDir: {}
      - name: logs
        emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-ai-backend
  namespace: cluster-ai
  labels:
    app: cluster-ai
    component: backend
spec:
  type: ClusterIP
  selector:
    app: cluster-ai
    component: backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
