import subprocess
import json
import time
from typing import Dict, Any, List
from datetime import datetime

def run_shell_script(script_path: str, args: list = []) -> str:
    """Execute a shell script and return its output"""
    try:
        result = subprocess.run([script_path] + args, capture_output=True, text=True, check=True)
        return result.stdout
    except subprocess.CalledProcessError as e:
        return ""

def parse_metrics_log(log_path: str) -> List[Dict[str, Any]]:
    """Parse metrics from log file"""
    metrics = []
    try:
        with open(log_path, "r") as f:
            for line in f:
                parts = line.strip().split(",")
                if len(parts) == 5:
                    timestamp, cpu, mem, disk, net = parts
                    metrics.append({
                        "timestamp": int(timestamp),
                        "cpu_percent": float(cpu),
                        "memory_percent": float(mem),
                        "disk_percent": float(disk),
                        "network_rx": float(net)
                    })
    except Exception:
        pass
    return metrics

def get_cluster_metrics() -> Dict[str, Any]:
    """Get cluster metrics from monitoring scripts"""
    # This function can be extended to parse cluster metrics from logs or APIs
    # For now, return dummy data or parse from files if available
    return {
        "ollama_running": True,
        "dask_running": True,
        "webui_running": True,
        "worker_count": 5,
        "dask_tasks_completed": 1000,
        "dask_tasks_failed": 5,
        "dask_tasks_pending": 10,
        "dask_tasks_processing": 3,
        "dask_total_workers": 5,
        "dask_active_workers": 5,
        "dask_memory_used": 1024 * 1024 * 1024,  # bytes
        "dask_scheduler_cpu": 15.0,
        "dask_scheduler_memory": 512,
        "dask_task_throughput": 20.0,
        "dask_avg_task_time": 0.05
    }

def get_system_metrics() -> List[Dict[str, Any]]:
    """Get system metrics from monitoring logs"""
    # Parse metrics log file generated by performance_dashboard.sh or central_monitor.sh
    metrics_log_path = "/home/dcm/Projetos/cluster-ai/logs/performance_history.log"
    return parse_metrics_log(metrics_log_path)

def get_alerts() -> List[str]:
    """Get alerts from monitoring logs"""
    alerts_log_path = "/home/dcm/Projetos/cluster-ai/logs/alerts.log"
    alerts = []
    try:
        with open(alerts_log_path, "r") as f:
            for line in f:
                alerts.append(line.strip())
    except Exception:
        pass
    return alerts

def get_workers_info() -> List[Dict[str, Any]]:
    """Get workers information from cluster monitoring"""
    # This can be extended to get real worker data from Dask or other sources
    return [
        {
            "id": "worker-001",
            "name": "Worker Node 1",
            "status": "active",
            "ip_address": "192.168.1.101",
            "cpu_usage": 45.2,
            "memory_usage": 67.8,
            "last_seen": datetime.now()
        },
        {
            "id": "worker-002",
            "name": "Worker Node 2",
            "status": "active",
            "ip_address": "192.168.1.102",
            "cpu_usage": 32.1,
            "memory_usage": 54.3,
            "last_seen": datetime.now()
        }
    ]
