{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cluster-ai.fullname" . }}-backend
  labels:
    {{- include "cluster-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "cluster-ai.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cluster-ai.backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cluster-ai.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: backend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.global.imageRegistry }}/{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: ENVIRONMENT
              value: {{ .Values.backend.env.environment | quote }}
            - name: REDIS_URL
              value: "redis://{{ include "cluster-ai.fullname" . }}-redis:6379"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "cluster-ai.fullname" . }}-secrets
                  key: postgres-connection-string
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "cluster-ai.fullname" . }}-secrets
                  key: secret-key
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "cluster-ai.fullname" . }}-secrets
                  key: jwt-secret-key
            - name: POSTGRES_HOST
              value: "{{ include "cluster-ai.fullname" . }}-postgresql"
            - name: POSTGRES_PORT
              value: "5432"
          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: logs
              mountPath: /app/logs
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      volumes:
        - name: data
          emptyDir: {}
        - name: logs
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cluster-ai.fullname" . }}-backend
  labels:
    {{- include "cluster-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cluster-ai.backend.selectorLabels" . | nindent 4 }}
{{- end }}
