apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cluster-ai.fullname" . }}-config
  labels:
    {{- include "cluster-ai.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.backend.env.environment | quote }}
  LOG_LEVEL: "INFO"
  TZ: "UTC"
  REDIS_MAX_MEMORY: "512mb"
  REDIS_MAX_MEMORY_POLICY: "allkeys-lru"
  PROMETHEUS_RETENTION: {{ .Values.prometheus.server.retention | quote }}
  ELASTICSEARCH_JAVA_OPTS: "-Xms1g -Xmx1g"
  NGINX_WORKER_PROCESSES: "auto"
  NGINX_WORKER_CONNECTIONS: "1024"
  NGINX_CLIENT_MAX_BODY_SIZE: "50M"
  FRONTEND_URL: {{ .Values.ingress.hosts | first | get "host" | printf "https://%s" }}
  BACKEND_URL: {{ .Values.ingress.hosts | last | get "host" | printf "https://%s" }}
