apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-ai.fullname" . }}-secrets
  labels:
    {{- include "cluster-ai.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  postgres-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  postgres-connection-string: {{ printf "postgresql://%s:%s@%s-postgresql:5432/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password (include "cluster-ai.fullname" .) .Values.postgresql.auth.database | b64enc | quote }}
  {{- end }}
  secret-key: {{ .Values.backend.env.secretKey | default (randAlphaNum 32) | b64enc | quote }}
  jwt-secret-key: {{ .Values.backend.env.jwtSecretKey | default (randAlphaNum 32) | b64enc | quote }}
  grafana-password: {{ .Values.grafana.adminPassword | b64enc | quote }}
  {{- if .Values.elasticsearch.enabled }}
  elastic-password: {{ .Values.elasticsearch.auth.password | default (randAlphaNum 16) | b64enc | quote }}
  {{- end }}
