kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: gcp-cluster
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "topology.kubernetes.io/region=us-central1,topology.kubernetes.io/zone=us-central1-a,cloud=gcp"
  extraPortMappings:
  - containerPort: 80
    hostPort: 8081
    protocol: TCP
  - containerPort: 443
    hostPort: 8444
    protocol: TCP
  - containerPort: 30000
    hostPort: 30002
    protocol: TCP
  - containerPort: 30001
    hostPort: 30003
    protocol: TCP
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "topology.kubernetes.io/region=us-central1,topology.kubernetes.io/zone=us-central1-b,cloud=gcp"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "topology.kubernetes.io/region=us-central1,topology.kubernetes.io/zone=us-central1-c,cloud=gcp"
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6444
  podSubnet: "10.245.0.0/16"
  serviceSubnet: "10.97.0.0/12"
